"""LangGraph State Definition for AIDA's Insight Brain.

Maintains immutable contract references, iterative investigation plans,
candidate insight pools, critic reviews, and verified/rejected audit lists.
"""

from __future__ import annotations
from typing import Any, Dict, List, Optional, TypedDict
from pydantic import BaseModel, Field, ConfigDict

from backend.aida.contracts.discovery_contract import DiscoveryContract
from backend.aida.contracts.analysis_contract import AnalysisContract
from backend.aida.contracts.insight_contract import (
    CandidateInsight,
    VerifiedInsight,
    RejectedInsight,
    InsightContract,
)


class Hypothesis(BaseModel):
    """Investigation thread generated by the Planner Node."""
    model_config = ConfigDict(extra="ignore")

    hypothesis_id: str = Field(..., description="Unique hypothesis identifier")
    focus_area: str = Field(
        ...,
        description="Category: 'correlation_analysis', 'anomaly_investigation', "
                    "'model_feature_drivers', 'distribution_outliers', 'data_quality_risk'",
    )
    description: str = Field(..., description="Hypothesis proposition to be tested")
    relevant_features: List[str] = Field(default_factory=list, description="Columns or models involved")
    priority: int = Field(default=1, ge=1, le=5, description="Priority score: 1 (highest) to 5 (lowest)")


class CritiqueEvaluation(BaseModel):
    """Adversarial critique generated by the Critic Node."""
    model_config = ConfigDict(extra="ignore")

    insight_id: str = Field(..., description="Candidate insight being evaluated")
    soundness_score: float = Field(..., ge=0.0, le=1.0, description="Logical soundness and clarity [0.0 - 1.0]")
    is_approved_for_verification: bool = Field(
        ..., description="True if logic is coherent and free from obvious contradictions"
    )
    critique_notes: str = Field(..., description="Specific feedback or sanity check details")
    concerns: List[str] = Field(default_factory=list, description="Any identified logical or business concerns")


class AidaState(TypedDict, total=False):
    """The central state dictionary traversing the LangGraph pipeline.

    Flow:
        Planner Node -> Investigator Node -> Critic Node -> Verifier Node
    """
    # Upstream Ground Truth Contracts
    discovery_contract: DiscoveryContract
    analysis_contract: AnalysisContract

    # Step 1: Investigation Plan (Planner Node output)
    investigation_plan: List[str]

    # Step 2: Candidates (Investigator Node output)
    candidate_insights: List[CandidateInsight]

    # Step 3: Critic Review (Critic Node output)
    critique_evaluations: List[CritiqueEvaluation]

    # Step 4: Verification (Verifier Node output - The Trust Layer)
    verified_insights: List[VerifiedInsight]
    rejected_insights: List[RejectedInsight]

    # Step 5: Ranking & Executive Summary (Ranker Node output)
    ranked_insights: List[VerifiedInsight]
    executive_summary: Optional[Dict[str, Any]]

    # Final Payload for Person 4
    insight_contract: Optional[InsightContract]

    # Pipeline metadata & error handling
    iteration: int
    errors: List[str]
    pipeline_errors: List[str]
